### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by NormanBB** [zzcabc/Rules#1]
1. 请问对于游戏分类，你是怎么制作的或者从哪个源获取的？

2.  对于`fallback-filter`中 `geoip` 应设置为`true`来过滤GeoIP。

**Comment by zzcabc** [comment]
1，本项目的大部分规则均使用旧库 https://github.com/lhie1/Rules (迁移至新库)新库 https://github.com/dler-io/Rules 和 https://github.com/ACL4SSR/ACL4SSR 合并而来，手动提取其中游戏规则(应该算是各大游戏官网的域名)合并到game文件内
2，关于`fallback-filter`的`geoip`为false，当初是用的openclash的`第三方规则订阅`来的，然后也没注意官方的文档

**Comment by zzcabc** [comment]
已改正geoip为true
